# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ndata.proto\"H\n\x06\x45ntity\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08\x65ntityId\x18\x02 \x01(\t\x12\x12\n\nentityType\x18\x03 \x01(\t\x12\n\n\x02id\x18\x04 \x01(\x05\"%\n\x08\x45ntities\x12\x19\n\x08\x65ntities\x18\x01 \x03(\x0b\x32\x07.Entityb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'data_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_ENTITY']._serialized_start=14
  _globals['_ENTITY']._serialized_end=86
  _globals['_ENTITIES']._serialized_start=88
  _globals['_ENTITIES']._serialized_end=125
# @@protoc_insertion_point(module_scope)
